CC=g++
CFLAGS=-c -Wall -std=c++17 -pthread
LDFLAGS=-pthread
SERVER_SOURCES=server.cpp database.cpp
CLIENT_SOURCES=client.cpp
SERVER_OBJECTS=$(SERVER_SOURCES:.cpp=.o)
CLIENT_OBJECTS=$(CLIENT_SOURCES:.cpp=.o)
SERVER_EXECUTABLE=server
CLIENT_EXECUTABLE=client

all: $(SERVER_SOURCES) $(CLIENT_SOURCES) $(SERVER_EXECUTABLE) $(CLIENT_EXECUTABLE)

$(SERVER_EXECUTABLE): $(SERVER_OBJECTS)
	$(CC) $(LDFLAGS) $(SERVER_OBJECTS) -o $@

$(CLIENT_EXECUTABLE): $(CLIENT_OBJECTS)
	$(CC) $(LDFLAGS) $(CLIENT_OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *o $(SERVER_EXECUTABLE) $(CLIENT_EXECUTABLE)
